# Generated by Django 5.0.1 on 2024-03-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
