# Generated by Django 5.0.1 on 2024-03-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_phone_contact_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='mail',
        ),
    ]
